# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ParseStarterProject-Swift' do

pod 'ParseFacebookUtilsV4'
pod 'FBSDKCoreKit', '~> 4.10'
pod 'FBSDKLoginKit', '~> 4.10'

end

